<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Catalog\Block\Product\View */
?>

<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php $url_data_sheet = $_product->getResource()->getAttribute('ficha_tecnica')->getFrontend()->getValue($_product); ?>
<?php $url_manual = $_product->getResource()->getAttribute('manual_de_uso')->getFrontend()->getValue($_product); ?>
<?php if ($_product->isSaleable()) :?>
<div class="bbox-tocart">
    <div class="fieldset">
        <?php if ($block->shouldRenderQuantity()) :?>
        <div class="field qty">
            <label class="label" for="qty"><span><?= $block->escapeHtml(__('Qty')) ?></span></label>
            <div class="control" data-bind="scope: 'qty_change'">
                <button class="decrease qty" data-bind="click: decreaseQty">-</button>
                <input data-bind="value: qty()"
                       type="number"
                       name="qty"
                       id="qty"
                       min="0"
                       title="<?= $block->escapeHtmlAttr(__('Qty')) ?>"
                       class="input-text qty"
                       data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                       maxlength="3"
                       maxAllowed="999"
                       />
                <button class="increase qty" data-bind="click: increaseQty">+</button>
            </div>
        </div>
        <?php endif; ?>
        <div class="actions">
            <button type="submit"
                    title="<?= $block->escapeHtmlAttr($buttonTitle) ?>"
                    class="action primary tocart"
                    id="product-addtocart-button" disabled>
                <span><?= $block->escapeHtml($buttonTitle) ?></span>
            </button>
            <?= $block->getChildHtml('', true) ?>
        </div>
    </div>
</div>
<?php endif; ?>
<span class="attribute sku"><?= __('Sku')?> <p><?=$_product->getSku()?></p></span>
<span class="product-additional-info">
    
   
    <?php if ($url_data_sheet): ?>
        <a class="data-sheet" href="<?= $url_data_sheet ?>" target="_blank" rel="noopener noreferrer"><?=__('Ficha tecnica')?></a>
    <?php endif; ?>
    <?php if ($url_manual): ?>
        <a class="manual" href="<?= $url_manual ?>" target="_blank" rel="noopener noreferrer"><?=__('Manual')?></a>
    <?php endif; ?>
</span>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "qty_change": {
                        "component": "Magento_Catalog/js/qty_change",
                        "defaultQty": <?php echo $block->getProductDefaultQty() * 1 ?>
                    }
                 }
            }
        }
    }
</script>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }
</script>
