<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * Product media data template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Gallery
 * @var $block \Magento\Catalog\Block\Product\View\AbstractView 
 */
?>

<?php $_product = $block->getProduct() ?>
<?php $productCategoryIds = $_product->getCategoryIds(); ?>
<?php $specialCategoryId = 4; ?>

<?php
$images = $block->getGalleryImages()->getItems();
$mainImage = current(array_filter($images, function ($img) use ($block) {
    return $block->isMainImage($img);
}));

if (!empty($images) && empty($mainImage)) {
    $mainImage = $block->getGalleryImages()->getFirstItem();
}

$helper = $block->getData('imageHelper');
$mainImageData = $mainImage ?
    $mainImage->getData('medium_image_url') :
    $helper->getDefaultPlaceholderUrl('image');

?>
<?php
$price = floatval($_product->getPrice());
$specialPrice = floatval($_product->getFinalPrice());
$discount = round(($price - $specialPrice)  / $price * 100); 
?>

<div class="gallery-placeholder _block-content-loading" data-gallery-role="gallery-placeholder">
    <?php if (in_array($specialCategoryId,$productCategoryIds)): ?>
        <img class="image-price-fugaces" src="<?php echo $this->getViewFileUrl('images/image-price-fugaces.png'); ?>" alt="image-price-fugaces">
    <?php endif; ?>
    <?php if ($price !== $specialPrice): ?>
        <span class="discount-rate"><?= "-" . $discount . "%" ?></span>
    <?php endif; ?>
    <img
        alt="main product photo"
        class="gallery-placeholder__image"
        src="<?= /* @noEscape */ $mainImageData ?>"
    />
</div>

<script type="text/x-magento-init">
    {
        "[data-gallery-role=gallery-placeholder]": {
            "mage/gallery/gallery": {
                "mixins":["magnifier/magnify"],
                "magnifierOpts": <?= /* @noEscape */ $block->getMagnifier() ?>,
                "data": <?= /* @noEscape */ $block->getGalleryImagesJson() ?>,
                "options": <?= /* @noEscape */ $block->getGalleryOptions()->getOptionsJson() ?>,
                "fullscreen": <?= /* @noEscape */ $block->getGalleryOptions()->getFSOptionsJson() ?>,
                 "breakpoints": <?= /* @noEscape */ $block->getBreakpoints() ?>
            }
        }
    }
</script>
